In [1]:
import numpy as np 
import pandas as pd

In [48]:
data = np.loadtxt("a_example.in")
rows,columns,n_vehicles,n_rides,bonus,steps = data[0,:]
actual_data = data[1:,:]
#row_start, column_start, row_end, column_end, earliest_start, latest finish
# print(actual_data)

def distance(a,b,c,d):
    return abs(a-c) + abs(b-d)

distance(actual_data[0,0], actual_data[0,1], actual_data[0,2], actual_data[0,3])


print("Rows:", rows)
print("Columns:", columns)
print("N_vehicles:", n_vehicles)
print("N_rides:", n_rides)
print("Bonus:", bonus)
print("Steps:", steps)

all_distance = distance(actual_data[:,0], actual_data[:,1], actual_data[:,2], actual_data[:,3])
data_with_distances = np.hstack((actual_data, np.reshape(all_distance, (actual_data.shape[0],1))))



print(data_with_distances)
data_with_distances.shape

Rows: 3.0
Columns: 4.0
N_vehicles: 2.0
N_rides: 3.0
Bonus: 2.0
Steps: 10.0
[[ 0.  0.  1.  3.  2.  9.  4.]
 [ 1.  2.  1.  0.  0.  9.  2.]
 [ 2.  0.  2.  2.  0.  9.  2.]]


(3, 7)

In [30]:
#last column is the latest start
data_with_latest_start = np.hstack((data_with_distances, np.reshape(data_with_distances[:,5]-data_with_distances[:,-1],(data_with_distances.shape[0],1))))
sorted_data = data_with_latest_start[data_with_latest_start[:,-1].argsort()]

#data sorted according to the latest start (last column)
print(sorted_data)


[[ 0.  0.  1.  3.  2.  9.  4.  5.]
 [ 1.  2.  1.  0.  0.  9.  2.  7.]
 [ 2.  0.  2.  2.  0.  9.  2.  7.]]


In [36]:
# data2 = np.loadtxt("b_should_be_easy.in")
# data2[0]

array([   800.,   1000.,    100.,    300.,     25.,  25000.])

In [112]:
#initialize if the car is occupied

def car_distance(ride_coords, car_coords):
    distances = []
    for car in car_coords:
        curr_dist = abs(ride_coords - car)
        distances.append(np.sum(curr_dist, axis=1))
    return np.array(distances)

#occupied
occupied = [0 for x in range(int(n_vehicles))]
car_last_coordinates = np.array([[0,0] for x in range(int(n_vehicles))])
# print(last_coordinates.shape)
starting_coords_rides = np.array([actual_data[:,0], actual_data[:,1]]).T
print(starting_coords_rides.shape)
distances = car_distance(starting_coords_rides, car_last_coordinates)
# print(distances)
when_earliest = actual_data[:,4]
print(when_earliest)
cost=np.zeros((int(n_rides), int(n_vehicles)))
print(len(distances))
print(len(when_earliest))
print(cost.shape)
print(cost-occupied)
# cost = occupied 
cost = (cost.T - distances + when_earliest).T + np.array(occupied)
print(cost)

(3, 2)
[ 2.  0.  0.]
2
3
(3, 2)
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
[[ 2.  2.]
 [-3. -3.]
 [-2. -2.]]


In [ ]:
for x in range(steps):
    