In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = np.loadtxt("a_example.in")
rows,columns,n_vehicles,n_rides,bonus,steps = data[0,:]
actual_data = data[1:,:]
#row_start, column_start, row_end, column_end, earliest_start, latest finish
print(actual_data)

def distance(a,b,c,d):
    return abs(a-c) + abs(b-d)

distance(actual_data[0,0], actual_data[0,1], actual_data[0,2], actual_data[0,3])

all_distance = distance(actual_data[:,0], actual_data[:,1], actual_data[:,2], actual_data[:,3])
data_with_distances = np.hstack((actual_data, np.reshape(all_distance, (actual_data.shape[0],1))))
print(data_with_distances)
data_with_distances.shape

[[ 0.  0.  1.  3.  2.  9.]
 [ 1.  2.  1.  0.  0.  9.]
 [ 2.  0.  2.  2.  0.  9.]]
[[ 0.  0.  1.  3.  2.  9.  4.]
 [ 1.  2.  1.  0.  0.  9.  2.]
 [ 2.  0.  2.  2.  0.  9.  2.]]


(3, 7)

In [3]:
#last column is the latest start
data_with_latest_start = np.hstack((data_with_distances, np.reshape(data_with_distances[:,5]-data_with_distances[:,-1],(data_with_distances.shape[0],1))))
sorted_data = data_with_latest_start[data_with_latest_start[:,-1].argsort()]

#data sorted according to the latest start (last column)
print(sorted_data)


[[ 0.  0.  1.  3.  2.  9.  4.  5.]
 [ 1.  2.  1.  0.  0.  9.  2.  7.]
 [ 2.  0.  2.  2.  0.  9.  2.  7.]]


In [15]:
submit = {'F0':[2, 0, 1],'F1':[1, 2]}

In [22]:
def calc_points(bonus, rides_data, submission_dict):
    assert isinstance(rides_data,(list,np.ndarray))
    assert isinstance(submission_dict,dict)
    dist_points = 0
    bonus_points = 0
    
    for f in submission_dict.keys():
        f_rides = submission_dict[f]
        assert len(f_rides) == f_rides[0] + 1, 'First number in list for each vehicle must equal the # of rides, occured for vehicle %s'%f
        
        f_position = np.array([0,0])
        t = 0
        for ride_num in f_rides[1:]:
            start_row,start_col,end_row,end_col,earliest_start,latest_finish,distance = rides_data[ride_num]
            print(rides_data[ride_num])
            dist_to_start = np.sum(np.abs(f_position - np.array([start_row,start_col])))
            t += dist_to_start
            
            if t < earliest_start:
                print('t less than earliest start %s, %s'%(t, earliest_start))
                bonus_points += bonus 
            
            dist_points += distance
            t = min(t,earliest_start) + distance
            f_position = [end_row,end_col]
            
            if t > latest_finish:
                print('Warning, vehicle %s could not complete ride %s on time, finished at %s, should have finished at %s'%(f,ride_num,t,latest_finish))
            
    return dist_points, bonus_points
            
            
            
        
        
        
    print(bonus, rides_data, submission_dict)
calc_points(bonus, data_with_distances, submit)

[ 0.  0.  1.  3.  2.  9.  4.]
t less than earliest start 0.0, 2.0
[ 1.  2.  1.  0.  0.  9.  2.]
[ 2.  0.  2.  2.  0.  9.  2.]


(8.0, 2.0)

In [ ]:
submit.