In [1]:
import numpy as np 
import pandas as pd

In [18]:
data = np.loadtxt("a_example.in")
rows,columns,n_vehicles,n_rides,bonus,steps = data[0,:]
actual_data = data[1:,:]
#row_start, column_start, row_end, column_end, earliest_start, latest finish
print(actual_data)

def distance(a,b,c,d):
    return abs(a-c) + abs(b-d)

distance(actual_data[0,0], actual_data[0,1], actual_data[0,2], actual_data[0,3])

all_distance = distance(actual_data[:,0], actual_data[:,1], actual_data[:,2], actual_data[:,3])
data_with_distances = np.hstack((actual_data, np.reshape(all_distance, (actual_data.shape[0],1))))
print(data_with_distances)
data_with_distances.shape

[[ 0.  0.  1.  3.  2.  9.]
 [ 1.  2.  1.  0.  0.  9.]
 [ 2.  0.  2.  2.  0.  9.]]
[[ 0.  0.  1.  3.  2.  9.  4.]
 [ 1.  2.  1.  0.  0.  9.  2.]
 [ 2.  0.  2.  2.  0.  9.  2.]]


(3, 7)

In [30]:
#last column is the latest start
data_with_latest_start = np.hstack((data_with_distances, np.reshape(data_with_distances[:,5]-data_with_distances[:,-1],(data_with_distances.shape[0],1))))
sorted_data = data_with_latest_start[data_with_latest_start[:,-1].argsort()]

#data sorted according to the latest start (last column)
print(sorted_data)


[[ 0.  0.  1.  3.  2.  9.  4.  5.]
 [ 1.  2.  1.  0.  0.  9.  2.  7.]
 [ 2.  0.  2.  2.  0.  9.  2.  7.]]
